version: '3'
services:
  app:
    build: ../
    environment:
      # 建议只使用英语与字母的flag，有横线的会导致dns获取失败
      FLAG: "flag{084e25616ea22945ba504ff0ff03cdfd}"
    ports:
      - 8080:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW

      